# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beaconapp', '0002_auto_20180313_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdf',
            new_name='event',
        ),
    ]
