# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beaconapp', '0003_auto_20180322_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktime',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='upgradeform',
            name='duration',
            field=models.CharField(default='1 on 1', max_length=200, verbose_name='Duration'),
        ),
    ]
