# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaconapp', '0004_auto_20180322_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeform',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='upgradeform',
            name='payment_method',
            field=models.CharField(max_length=200, null=True, verbose_name='Payment Method'),
        ),
    ]
