# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('beaconapp', '0001_initial'),
        ('staff', '0001_initial'),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('grade_entered', models.DateField(auto_now=True, verbose_name='Grade entered')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('zip', models.CharField(max_length=30, verbose_name='Zip code')),
                ('heard_from', models.CharField(max_length=200, verbose_name='Heard from')),
                ('heard_from_other', models.CharField(max_length=200, null=True, verbose_name='Heard from other')),
                ('purpose', models.TextField(null=True, verbose_name='Purpose')),
                ('active', models.BooleanField(default=False, verbose_name='Is active')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('start_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('referred_by', models.CharField(max_length=200, null=True)),
                ('enrichment_id', models.PositiveIntegerField(null=True)),
                ('review', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_created_by', to='staff.Staff')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classapp.Grade')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_modified_by', to='staff.Staff')),
                ('parents', models.ManyToManyField(related_name='student', to='parents.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/files', verbose_name='File')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True, verbose_name='Status')),
                ('classwork', models.CharField(max_length=200, null=True, verbose_name='Classwork')),
                ('homework', models.CharField(max_length=200, null=True, verbose_name='Homework')),
                ('cc_lesson_plan_id', models.PositiveIntegerField(null=True)),
                ('cc_classwork', models.CharField(max_length=200, null=True)),
                ('cc_homework', models.CharField(max_length=200, null=True)),
                ('finished_classwork', models.CharField(max_length=200, null=True)),
                ('finished_homework', models.CharField(max_length=200, null=True)),
                ('fixups_done', models.CharField(max_length=200, null=True)),
                ('mentals', models.CharField(max_length=200, null=True)),
                ('comments', models.TextField(max_length=200, null=True)),
                ('duration', models.CharField(default='1 Hour', max_length=200)),
                ('time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassRollout')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_in_class_created_by', to='staff.Staff')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_in_class_modified_by', to='staff.Staff')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note text')),
                ('note_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_created_by', to='staff.Staff', verbose_name='Created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_note_event', to='beaconapp.Timeline')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_modified_by', to='staff.Staff', verbose_name='Modified by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student')),
            ],
        ),
    ]
