# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_entered',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Grade entered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentinclass',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentinclass',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Modified date'),
        ),
    ]
