# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180322_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
