# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20180327_0724'),
        ('students', '0003_auto_20180322_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referred_by_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_referred_by_staff', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='student',
            name='referred_by_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_referred_by_student', to='students.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
