# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180327_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHeardFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
            ],
        ),
    ]
