# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180329_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referred_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_referred_by_staff', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='referred_by_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_referred_by_student', to='students.Student'),
        ),
    ]
