# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180329_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
