# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='students.StudentStatus'),
            preserve_default=False,
        ),
    ]
