# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_entered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Grade entered'),
        ),
    ]
