# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20180601_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='street_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Street'),
        ),
        migrations.AlterField(
            model_name='studentinclass',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassRollout'),
        ),
    ]
