# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0031_auto_20180628_0933'),
        ('students', '0017_auto_20180609_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='last_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassRollout'),
        ),
    ]
