# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_studentinclass_last_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='gc_parent_event_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Google Calendar Event Id'),
        ),
        migrations.AlterField(
            model_name='studentinclass',
            name='last_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_students', to='classapp.ClassRollout'),
        ),
    ]
