# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20180725_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_cancelled', to='students.StudentInClass', verbose_name='Cancelled class')),
                ('makeup_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_new', to='students.StudentInClass', verbose_name='Makeup class')),
            ],
        ),
    ]
