# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_staff_locations'),
        ('students', '0021_auto_20180727_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmakeup',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='studentmakeup',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Created by'),
        ),
    ]
