# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_studentfiles_exam_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfiles',
            old_name='exam_record',
            new_name='multiple',
        ),
    ]
