# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20180823_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='week',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
