# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_studentinclass_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='attendance',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='fluency_rg',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='ideas_rg',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='organisation_rg',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='presentation_rg',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='request_book',
            field=models.BooleanField(default=False),
        ),
    ]
