# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_auto_20181212_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinclass',
            name='finished_classwork',
        ),
        migrations.RemoveField(
            model_name='studentinclass',
            name='finished_homework',
        ),
        migrations.RemoveField(
            model_name='studentinclass',
            name='fixups_done',
        ),
        migrations.RemoveField(
            model_name='studentinclass',
            name='mentals',
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='finished_classwork_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='finished_homework_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='fixups_done_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='mentals_b',
            field=models.BooleanField(default=False),
        ),
    ]
