# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20181213_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='comp_book',
            field=models.BooleanField(default=False),
        ),
    ]
