# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0042_lessonplan_lp_id'),
        ('students', '0030_studentinclass_comp_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='next_lesson_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_students', to='classapp.LessonPlan'),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='selected_lesson_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='classapp.LessonPlan'),
        ),
    ]
