# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0043_auto_20181219_0225'),
        ('students', '0031_auto_20181218_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_for_book', to='classapp.Book'),
        ),
    ]
