# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_studentinclass_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmakeup',
            name='original_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makeup_original', to='students.StudentInClass', verbose_name='Original class'),
        ),
    ]
