# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_auto_20181226_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='c_comments',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='c_next_classwork',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='c_next_homework',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentinclass',
            name='c_request_book',
            field=models.BooleanField(default=False),
        ),
    ]
