# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-14 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_auto_20181228_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='wpm',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
