# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0046_auto_20190222_0313'),
        ('students', '0038_studentinclass_wpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBookPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classwork', models.CharField(max_length=256, null=True, verbose_name='Classwork')),
                ('homework', models.CharField(max_length=256, null=True, verbose_name='Homework')),
                ('lesson_plan_id', models.PositiveIntegerField(null=True)),
                ('next_classwork', models.CharField(max_length=256, null=True)),
                ('next_homework', models.CharField(max_length=256, null=True)),
                ('finished_classwork', models.BooleanField(default=False)),
                ('finished_homework', models.BooleanField(default=False)),
                ('fixups_done', models.BooleanField(default=False)),
                ('mentals', models.BooleanField(default=False)),
                ('comp_book', models.BooleanField(default=False)),
                ('comments', models.TextField(max_length=256, null=True)),
                ('request_book', models.BooleanField(default=False)),
                ('ideas_rg', models.CharField(max_length=64, null=True)),
                ('organisation_rg', models.CharField(max_length=64, null=True)),
                ('fluency_rg', models.CharField(max_length=64, null=True)),
                ('presentation_rg', models.CharField(max_length=64, null=True)),
                ('manager_note', models.TextField(max_length=256, null=True)),
                ('wpm', models.TextField(max_length=256, null=True)),
                ('request_conference', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_book_plan', to='classapp.Book')),
                ('next_lesson_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_books', to='classapp.LessonPlan')),
                ('selected_lesson_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_books', to='classapp.LessonPlan')),
                ('sic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='students.StudentInClass')),
            ],
        ),
    ]
