# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classapp', '0001_initial'),
        ('parents', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='studentconference',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_conference', to='classapp.Book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='studentconference',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_event_conference', to='beaconapp.Timeline', verbose_name='Timeline event'),
        ),
        migrations.AddField(
            model_name='studentconference',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_material', to='classapp.Material', verbose_name='Related material given'),
        ),
        migrations.AddField(
            model_name='studentconference',
            name='parents',
            field=models.ManyToManyField(null=True, related_name='parents', to='parents.Parent', verbose_name='Parents'),
        ),
        migrations.AddField(
            model_name='studentconference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_conference', to='students.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location'),
        ),
        migrations.AddField(
            model_name='material',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_book_given', to='classapp.Book', verbose_name='Book given'),
        ),
        migrations.AddField(
            model_name='material',
            name='last_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.Book', verbose_name='Last book given'),
        ),
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location'),
        ),
        migrations.AddField(
            model_name='material',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_material', to='students.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_subject', to='classapp.Subject', verbose_name='Material subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_teacher', to='staff.Staff', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_manager', to='staff.Staff', verbose_name='Location manager'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subject', to='classapp.Subject', verbose_name="Course's subject"),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_def', to='classapp.ClassDefinition', verbose_name='Class definition'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_created_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_modified_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Room'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Staff id'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='classapp.Room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='staff.Staff', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='classapp.Subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='booksgiven',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_given', to='classapp.Book', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='booksgiven',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_created_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='booksgiven',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_modified_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='booksgiven',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='bookexam',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='classapp.Book', verbose_name='book_exam'),
        ),
        migrations.AddField(
            model_name='bookexam',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_material', to='classapp.Material', verbose_name='Related material'),
        ),
        migrations.AddField(
            model_name='bookexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bookexam', to='students.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_course', to='classapp.Course', verbose_name='Book course'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_subject', to='classapp.Subject', verbose_name='Book subject'),
        ),
    ]
