# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_auto_20180322_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
    ]
