# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20180403_0628'),
        ('classapp', '0004_auto_20180330_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconference',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_staff', to='staff.Staff', verbose_name='Staff'),
        ),
    ]
