# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_studentconference_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconference',
            name='staff',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='conference_staff', to='staff.Staff', verbose_name='Staff'),
            preserve_default=False,
        ),
    ]
