# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_auto_20180403_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconference',
            name='gift_card',
            field=models.TextField(null=True, verbose_name='Gift Card'),
        ),
    ]
