# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0007_studentconference_gift_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconference',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
