# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beaconapp', '0004_auto_20180322_0724'),
        ('parents', '0005_auto_20180507_1011'),
        ('staff', '0025_auto_20180403_0809'),
        ('students', '0014_auto_20180507_1011'),
        ('classapp', '0008_studentconference_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_book_given_log', to='classapp.Book', verbose_name='Book given')),
                ('last_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_teacher_log', to='classapp.Book', verbose_name='Last book given')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location')),
                ('modification_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_log_modification_object', to='classapp.Material', verbose_name='Modification Object')),
                ('modification_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_log_modification_staff', to='staff.Staff', verbose_name='Modification Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_material_log', to='students.Student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_subject_log', to='classapp.Subject', verbose_name='Material subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_teacher_log', to='staff.Staff', verbose_name='Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentConferenceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('date', models.DateField()),
                ('review', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True, verbose_name='Comments/Notes')),
                ('gift_card', models.TextField(null=True, verbose_name='Gift Card')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_book', to='classapp.Book', verbose_name='book')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_event', to='beaconapp.Timeline', verbose_name='Timeline event')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_material', to='classapp.Material', verbose_name='Related material given')),
                ('modification_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_modification_object', to='classapp.StudentConference', verbose_name='Modification Object')),
                ('modification_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_modification_staff', to='staff.Staff', verbose_name='Modification Staff')),
                ('parents', models.ManyToManyField(null=True, related_name='conference_log_parents', to='parents.Parent', verbose_name='Parents')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_staff', to='staff.Staff', verbose_name='Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_log_student', to='students.Student', verbose_name='Student')),
            ],
        ),
        migrations.AlterField(
            model_name='classrollout',
            name='class_date',
            field=models.DateTimeField(verbose_name='Class date'),
        )
    ]
