# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0009_auto_20180507_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksgiven',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksgiven',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='booksgiven',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='booksgiven',
            name='student',
        ),
        migrations.DeleteModel(
            name='BooksGiven',
        ),
    ]
