# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0010_auto_20180507_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentconference',
            old_name='review',
            new_name='review_solicited',
        ),
    ]
