# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0012_studentconference_review_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentconferencelog',
            old_name='review',
            new_name='review_solicited',
        ),
    ]
