# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0013_auto_20180507_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconferencelog',
            name='review_received',
            field=models.BooleanField(default=False),
        ),
    ]
