# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0014_studentconferencelog_review_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='classduration',
            name='hours',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
