# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0015_classduration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classduration',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
