# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0018_classdefinition_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='classduration',
            name='duration_short_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
