# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0019_auto_20180517_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrollout',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout', to='classapp.ClassDefinition', verbose_name='Class definition'),
        ),
    ]
