# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0021_auto_20180530_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdefinition',
            name='event_title',
            field=models.CharField(default='1', max_length=500, verbose_name='Event Title'),
            preserve_default=False,
        ),
    ]
