# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0025_auto_20180618_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexam',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_exam', to='classapp.Book', verbose_name='Book'),
        ),
    ]
