# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-22 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_staff_locations'),
        ('classapp', '0026_auto_20180620_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRolloutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Max capacity of class')),
                ('class_status', models.CharField(default='modified', max_length=200, verbose_name='Class status')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('class_date', models.DateTimeField(verbose_name='Class date')),
                ('comments', models.CharField(max_length=300, null=True)),
                ('gc_event_id', models.CharField(max_length=200, null=True, verbose_name='Google Calendar Event Id')),
                ('gc_event_title', models.CharField(max_length=500, verbose_name='Google Calendar Event Title')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout_log', to='classapp.ClassDefinition', verbose_name='Class definition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_log_created_by', to='staff.Staff')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Location')),
                ('modification_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout_log_modification_object', to='classapp.ClassRollout', verbose_name='Modification Object')),
                ('modification_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout_log_modification_staff', to='staff.Staff', verbose_name='Modification Staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Room')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Staff id')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Subject', verbose_name='Subject')),
            ],
        ),
    ]
