# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0028_classrollout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrolloutlog',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout_log', to='classapp.ClassDuration'),
            preserve_default=False,
        ),
    ]
