# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0029_classrolloutlog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrollout',
            name='class_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('present', 'present'), ('absent', 'absent'), ('cancelled', 'cancelled'), ('break', 'break'), ('discontinued', 'discontinued'), ('makeup', 'makeup'), ('modified', 'modified')], default='scheduled', max_length=200, verbose_name='Class status'),
        ),
    ]
