# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0030_auto_20180627_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrollout',
            name='comments',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
