# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0033_room_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrollout',
            name='show_while_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
