# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-10 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0035_lessonplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='book',
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='extended',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LessonPlan',
        ),
    ]
