# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0040_auto_20181212_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrollout',
            name='weekly_report_changed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
