# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0041_classrollout_weekly_report_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lp_id',
            field=models.CharField(max_length=256, null=True, verbose_name='Lesson plan ID'),
        ),
    ]
