# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0042_lessonplan_lp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassDuration', verbose_name='Duration in lesson plan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.Subject', verbose_name='Subject in lesson plan'),
        ),
    ]
