# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0043_auto_20181219_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=128, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Subject', verbose_name='Activity subject')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classrollout',
            name='writing_prompt',
            field=models.CharField(max_length=512, null=True, verbose_name='Writing prompt'),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='yoga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classrollout',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassActivity'),
        ),
    ]
