# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-18 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0044_auto_20190214_0331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingPrompt',
            new_name='WritingPrompt',
        ),
    ]
