# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0045_auto_20190218_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='gd_link',
            field=models.CharField(max_length=512, null=True, verbose_name='Google Drive link'),
        ),
        migrations.AddField(
            model_name='material',
            name='request_conference_date',
            field=models.DateTimeField(null=True),
        ),
    ]
