# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 10:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaconapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('personal_email', models.CharField(max_length=50, null=True, verbose_name='Personal email')),
                ('street', models.CharField(max_length=200, null=True, verbose_name='Street')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('zip', models.CharField(max_length=20, null=True, verbose_name='Zip code')),
                ('hire_date', models.DateField(null=True, verbose_name='Hire date')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('referred_by_staff_id', models.PositiveIntegerField(null=True, verbose_name='Reffered by')),
                ('photo', models.FileField(null=True, upload_to='media/photos', verbose_name='Photo')),
                ('admin_flag', models.BooleanField(default=False, verbose_name='Is admin')),
                ('manager_flag', models.BooleanField(default=False, verbose_name='Is manager')),
                ('teacher_flag', models.BooleanField(default=True, verbose_name='Is teacher')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('subjects', models.ManyToManyField(related_name='staff_subjects', to='classapp.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note text')),
                ('note_type', models.CharField(max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_note_created_by', to='staff.Staff', verbose_name='Created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_note_event', to='beaconapp.Timeline')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_note_modified_by', to='staff.Staff', verbose_name='Modified by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_note', to='staff.Staff', verbose_name='Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2000)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2018, 3, 13, 11, 39, 53, 122492))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
