# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20180322_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 14, 9, 55, 650850)),
        ),
    ]
