# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20180329_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 7, 50, 19, 473507)),
        ),
    ]
