# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20180330_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 9, 23, 14, 53664)),
        ),
    ]
