# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0009_auto_20180507_1011'),
        ('staff', '0025_auto_20180403_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
