# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0041_classrollout_weekly_report_changed_date'),
        ('staff', '0027_staff_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='default_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.Location'),
        ),
    ]
