# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_staff_default_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='default_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classapp.Location'),
        ),
    ]
