# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_auto_20180330_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='alternate_phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Alternate phone'),
        ),
    ]
