# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_auto_20180507_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell phone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home phone'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
    ]
