# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_auto_20180513_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
